apiVersion: apps/v1
kind: Deployment
metadata:
  name: $(NAME)
  labels:
    app.kubernetes.io/name: $(NAME)
    app.kubernetes.io/component: payara-app
    app.kubernetes.io/part-of: $(ID)
    app.kubernetes.io/managed-by: payara-cloud     
    #app.kubernetes.io/version: $(VERSION)
  annotations:
    # These annotations define the deployment
    # Variables like NAME, PROJECT, STAGE are fetched from these
    payara.cloud/artifact-url: $(URL)
    #payara.cloud/artifact-version: XXX
    payara.cloud/project: $(PROJECT)
    payara.cloud/stage: $(STAGE)
    payara.cloud/artifact: $(NAME)
    payara.cloud/domain: $(DOMAIN)
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: $(NAME)
      app.kubernetes.io/part-of: $(ID)
      app.kubernetes.io/component: payara-app
  template:
    metadata:
      name: $(ID)
      labels:
        app.kubernetes.io/name: $(NAME)
        app.kubernetes.io/instance: $(NAME)
        app.kubernetes.io/component: payara-app
        app.kubernetes.io/part-of: $(ID)
        app.kubernetes.io/managed-by: payara-cloud   
      annotations:
        payara.cloud/artifact-url: $(URL)
    spec:
      initContainers:
        - name: download-app
          # This curl image downloads the artifacts from URL in annotation
          # into deployments volume
          image: curlimages/curl:latest
          command:
            - sh
          args: ["-c", "cd /deployments && curl -O `cat /podinfo/url`"]
          volumeMounts:
            - mountPath: /deployments
              name: deployments
            - mountPath: /podinfo
              name: podinfo
      containers:
      - name: micro
        image: payara/micro:jdk11
        volumeMounts:
          - mountPath: /opt/payara/deployments
            name: deployments
        # DNS cluster mode allows for instances of same app cluster themselves without need for Kubernetes API access
        # "--clustermode", "dns:$(NAME)-datagrid:6900"
        # but still has startup time cost, so for demo we switch it off
        args: ["--deploymentDir", "/opt/payara/deployments", "--nocluster"]
        resources:
          # Allocate quarter of CPU at rest, allow for use up to 1 CPU.
          requests:
            cpu: 250m
          limits:
            memory: "512Mi"
            # disable for snappier demo
            # cpu: "1"
        ports:
          - containerPort: 8080
            name: http
          - containerPort: 6900
            name: datagrid
        # poll hard at startup, then in regular periods (Since 1.16)
        startupProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 3
          periodSeconds: 1
          failureThreshold: 120
        livenessProbe:
          httpGet:
            path: /health
            port: http
          failureThreshold: 3
          initialDelaySeconds: 60
        # Kubernetes 1.14 doesn't know startup probe yet, let's use readyness
        # so that we don't announce failed deployment as success
        readinessProbe:
          httpGet:
            path: /health
            port: http
          failureThreshold: 1   
          periodSeconds: 2
          initialDelaySeconds: 3
      volumes:
        - name: deployments
          emptyDir: 
        - name: podinfo
          downwardAPI:
            items:
              - path: url
                # put url from annotation into /podinfo/url
                fieldRef:
                  fieldPath: metadata.annotations['payara.cloud/artifact-url']